<template><view class="page"><view class="hero"><text class="title">未来职业猜猜看</text><text class="intro">观察职业场景，探索未来职业世界。</text></view><button type="primary" :loading="loading" @click="start">开始游戏</button></view></template>
<script>
import { enterRecord, getRecord, startRecord, userMessage } from '@/api/zycck'
export default { data: () => ({ instanceId: '', gameId: '', recordId: '', loading: false }), async onLoad(o) { this.instanceId = o.instanceId || o.activityId || ''; this.gameId = o.gameId || ''; this.recordId = o.recordId || ''; if (!this.recordId && this.instanceId && this.gameId) await this.ensureRecord() }, methods: {
  async ensureRecord() { try { const entered = await enterRecord({ instanceId: this.instanceId, gameId: this.gameId, gameType: 'zycck', schoolId: uni.getStorageSync('schoolId') }); this.recordId = entered && entered.data && (entered.data.recordId || entered.data.id); if (!this.recordId) throw new Error('记录创建失败') } catch (e) { uni.showToast({ title: userMessage(e, '游戏入口校验失败，请重新扫码'), icon: 'none' }) } },
  async start() { if (this.loading) return; if (!this.instanceId || !this.gameId) return uni.showToast({ title: '二维码缺少活动信息，请重新扫码', icon: 'none' }); if (!this.recordId) { await this.ensureRecord(); if (!this.recordId) return }; this.loading = true; const base = `recordId=${encodeURIComponent(this.recordId)}&instanceId=${encodeURIComponent(this.instanceId)}&gameId=${encodeURIComponent(this.gameId)}`; try { const current = await getRecord(this.recordId); const currentData = current.data || {}; const currentRecord = currentData.record || currentData; if (currentData.status === 'finished' || currentRecord.status === 'finished') return uni.redirectTo({ url: `/pages/zycck/exploration-list?${base}&readOnly=1` }); const res = await startRecord(this.recordId); const data = res.data || {}; if (data.stage === 'feedback') uni.redirectTo({ url: `/pages/zycck/feedback?${base}` }); else if (data.stage === 'summary') uni.redirectTo({ url: `/pages/zycck/summary?${base}` }); else if (data.stage === 'exploration' || data.status === 'finished') uni.redirectTo({ url: `/pages/zycck/exploration-list?${base}&readOnly=${data.status === 'finished' ? '1' : '0'}` }); else uni.redirectTo({ url: `/pages/zycck/question?${base}&stage=${encodeURIComponent(data.stage || '')}` }) } catch (e) { uni.showToast({ title: userMessage(e, '游戏启动失败，请稍后重试'), icon: 'none' }) } finally { this.loading = false } }
} }
</script>
<style scoped>.page{min-height:100vh;padding:48rpx 56rpx;box-sizing:border-box;background:#f5f7fb;display:flex;flex-direction:column;justify-content:center}.hero{text-align:center;margin-bottom:72rpx}.title{display:block;font-size:52rpx;font-weight:700;color:#1a2c4a}.intro{display:block;margin-top:24rpx;color:#667085;font-size:28rpx}</style>
